### ISSUE TITLE
Bug avec le scaling de Windows

### ISSUE THREAD

**Issue by SamaelHeaven** [T1WiLLi/PPS#100]
La fenêtre semble ne pas prendre en compte le scaling: 
https://stackoverflow.com/questions/32586883/windows-scaling
![Screenshot 2024-11-14 122631](https://github.com/user-attachments/assets/80d70155-5b13-4e01-af77-5b2414539c89)
![Screenshot 2024-11-14 122647](https://github.com/user-attachments/assets/09177c3e-091b-40a8-a552-e47fc615e133)

**Comment by T1WiLLi** [comment]
@SamaelHeaven Merci ! 

As-tu des informations supplémentaire dans la console ? 
Est-ce que sa arrive uniquement dans le menu ou également dans le jeu ?
